# Generated by Django 4.0.4 on 2024-05-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main_Icon',
            field=models.ImageField(null=True, upload_to='category_Icon/'),
        ),
    ]
