# Generated by Django 4.0.4 on 2024-05-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_productimage_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='main_image',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
    ]
