# Generated by Django 4.0.4 on 2024-05-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_remove_productimage_main_image_product_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='starting_price',
        ),
    ]
