# Generated by Django 5.0.6 on 2024-06-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auctionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionrequest',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
    ]
