# Generated by Django 5.0.6 on 2024-06-04 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_alter_auctionrequest_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionrequest',
            name='auction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.auction'),
        ),
    ]
