# Generated by Django 5.0.6 on 2024-06-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_remove_auctionrequest_auction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='is_active',
        ),
    ]
