# Generated by Django 5.0.6 on 2024-06-26 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_alter_auctionrequest_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='winning_price',
            new_name='winning_bid',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='product',
        ),
        migrations.AddField(
            model_name='winner',
            name='auction',
            field=models.ForeignKey(default=37, on_delete=django.db.models.deletion.CASCADE, to='auction.auction'),
            preserve_default=False,
        ),
    ]
